// Cache-first app-shell service worker. Bump VERSION on every deploy.
const VERSION = 'exercises-v12';
const SHELL = [
  './',
  'index.html',
  'css/style.css',
  'js/app.js',
  'js/data.js',
  'js/gen-manifest.js',
  'js/store.js',
  'js/routine.js',
  'manifest.webmanifest',
  'icons/favicon.svg',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-512.png',
  'img/ab-iso-hold.svg',
  'img/ab-machine.svg',
  'img/ankle-cars.svg',
  'img/ankle-rocks.svg',
  'img/arch-pointe-stretch.svg',
  'img/back-extension.svg',
  'img/bench-press-decline.svg',
  'img/bench-press-flat.svg',
  'img/bench-press-incline.svg',
  'img/bridge-hold.svg',
  'img/bulgarian-split-squat.svg',
  'img/butterfly.svg',
  'img/cable-curl-single.svg',
  'img/calf-press.svg',
  'img/calf-raise-single.svg',
  'img/calf-raise.svg',
  'img/calf-stretch.svg',
  'img/cat-cow.svg',
  'img/chest-opener.svg',
  'img/chest-press.svg',
  'img/childs-side-reach.svg',
  'img/chin-up.svg',
  'img/concentration-curl.svg',
  'img/constructive-rest.svg',
  'img/cossack.svg',
  'img/couch-stretch.svg',
  'img/crossover-single.svg',
  'img/crunches.svg',
  'img/curl-21s.svg',
  'img/dead-hang.svg',
  'img/deep-squat-hold.svg',
  'img/diamond-push-up.svg',
  'img/down-dog-flow.svg',
  'img/dumbbell-bench-press.svg',
  'img/dumbbell-row-single.svg',
  'img/elephant-walks.svg',
  'img/figure-four.svg',
  'img/foot-doming.svg',
  'img/forward-fold.svg',
  'img/french-press-cable.svg',
  'img/french-press-single.svg',
  'img/frog-hold.svg',
  'img/frog-rocks.svg',
  'img/front-split.svg',
  'img/glute-bridge.svg',
  'img/half-split.svg',
  'img/hinge-fold.svg',
  'img/hip-abductor-iso.svg',
  'img/hip-abductor.svg',
  'img/hip-adductor-iso.svg',
  'img/hip-adductor.svg',
  'img/hip-airplane.svg',
  'img/hip-cars.svg',
  'img/hip-raise-ball.svg',
  'img/hip-raise-step.svg',
  'img/hip-thrust.svg',
  'img/horse-stance.svg',
  'img/hurdler.svg',
  'img/incline-dumbbell-fly.svg',
  'img/incline-push-up.svg',
  'img/inner-thigh-raise.svg',
  'img/knee-push-up.svg',
  'img/lat-machine-single.svg',
  'img/lat-machine.svg',
  'img/lat-pulldown-underhand.svg',
  'img/leg-curl-lying-single.svg',
  'img/leg-curl-lying.svg',
  'img/leg-curl-standing.svg',
  'img/leg-extension-ankle.svg',
  'img/leg-extension-both.svg',
  'img/leg-extension-cable.svg',
  'img/leg-extension-iso.svg',
  'img/leg-extension-single.svg',
  'img/leg-press-45.svg',
  'img/leg-press-90.svg',
  'img/leg-press-horizontal.svg',
  'img/lizard.svg',
  'img/low-lunge.svg',
  'img/lunge-halfsplit-flow.svg',
  'img/lunge-pulses.svg',
  'img/neck-rolls.svg',
  'img/negative-pull-up.svg',
  'img/ninety-ninety.svg',
  'img/pancake-fold.svg',
  'img/pec-deck.svg',
  'img/pigeon.svg',
  'img/point-flex.svg',
  'img/preacher-curl.svg',
  'img/psoas-march.svg',
  'img/pull-up.svg',
  'img/puppy-pose.svg',
  'img/push-up.svg',
  'img/releve-holds.svg',
  'img/rolldown.svg',
  'img/rope-pulldown.svg',
  'img/row-horizontal-machine.svg',
  'img/scapular-pull.svg',
  'img/seated-row-high.svg',
  'img/seated-row-low.svg',
  'img/seated-row-mid.svg',
  'img/side-leg-raise.svg',
  'img/single-leg-hamstring.svg',
  'img/smith-bench-press.svg',
  'img/smith-lunge.svg',
  'img/soleus-stretch.svg',
  'img/sphinx-cobra.svg',
  'img/split-pnf.svg',
  'img/standing-hip-ext.svg',
  'img/standing-quad.svg',
  'img/straddle-center.svg',
  'img/straddle-side-reach.svg',
  'img/sumo-squat.svg',
  'img/supine-twist.svg',
  'img/thoracic-rotation.svg',
  'img/toe-stretch-kneel.svg',
  'img/triceps-pushdown-single.svg',
  'img/triceps-pushdown.svg',
  'img/v-bar-pulldown.svg',
  'img/wall-straddle.svg',
  'img/wide-leg-fold.svg',
  'img/wide-push-up.svg',
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== location.origin) return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(hit =>
      hit ||
      fetch(e.request).then(res => {
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put(e.request, copy));
        return res;
      }).catch(() => (e.request.mode === 'navigate' ? caches.match('./') : undefined))
    )
  );
});
