// Cache-first app-shell service worker. Bump VERSION on every deploy.
const VERSION = "exercises-v23";
const SHELL = [
  "./",
  "index.html",
  "css/style.css",
  "js/app.js",
  "js/data.js",
  "js/store.js",
  "js/sync.js",
  "js/routine.js",
  "manifest.webmanifest",
  "icons/icon.svg",
  "icons/icon-180.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "img/gen/ab-iso-hold.webp",
  "img/gen/ab-machine.webp",
  "img/gen/ankle-cars.webp",
  "img/gen/ankle-rocks.webp",
  "img/gen/arch-pointe-stretch.webp",
  "img/gen/back-extension.webp",
  "img/gen/bench-press-decline.webp",
  "img/gen/bench-press-flat.webp",
  "img/gen/bench-press-incline.webp",
  "img/gen/bridge-hold.webp",
  "img/gen/bulgarian-split-squat.webp",
  "img/gen/butterfly.webp",
  "img/gen/cable-curl-single.webp",
  "img/gen/calf-press.webp",
  "img/gen/calf-raise-single.webp",
  "img/gen/calf-raise.webp",
  "img/gen/calf-stretch.webp",
  "img/gen/cat-cow.webp",
  "img/gen/chest-opener.webp",
  "img/gen/chest-press.webp",
  "img/gen/chin-up.webp",
  "img/gen/concentration-curl.webp",
  "img/gen/cossack.webp",
  "img/gen/couch-stretch.webp",
  "img/gen/crossover-single.webp",
  "img/gen/crunches.webp",
  "img/gen/curl-21s.webp",
  "img/gen/dead-hang.webp",
  "img/gen/deep-squat-hold.webp",
  "img/gen/diamond-push-up.webp",
  "img/gen/down-dog-flow.webp",
  "img/gen/dumbbell-bench-press.webp",
  "img/gen/dumbbell-row-single.webp",
  "img/gen/elephant-walks.webp",
  "img/gen/figure-four.webp",
  "img/gen/foot-doming.webp",
  "img/gen/forward-fold.webp",
  "img/gen/french-press-cable.webp",
  "img/gen/french-press-single.webp",
  "img/gen/frog-hold.webp",
  "img/gen/frog-rocks.webp",
  "img/gen/front-split.webp",
  "img/gen/glute-bridge.webp",
  "img/gen/half-split.webp",
  "img/gen/hinge-fold.webp",
  "img/gen/hip-abductor-iso.webp",
  "img/gen/hip-abductor.webp",
  "img/gen/hip-adductor-iso.webp",
  "img/gen/hip-adductor.webp",
  "img/gen/hip-airplane.webp",
  "img/gen/hip-cars.webp",
  "img/gen/hip-raise-ball.webp",
  "img/gen/hip-raise-step.webp",
  "img/gen/hip-thrust.webp",
  "img/gen/horse-stance.webp",
  "img/gen/hurdler.webp",
  "img/gen/incline-dumbbell-fly.webp",
  "img/gen/incline-push-up.webp",
  "img/gen/inner-thigh-raise.webp",
  "img/gen/jefferson-curl.webp",
  "img/gen/knee-push-up.webp",
  "img/gen/lat-machine-single.webp",
  "img/gen/lat-machine.webp",
  "img/gen/lat-pulldown-underhand.webp",
  "img/gen/leg-curl-lying-single.webp",
  "img/gen/leg-curl-lying.webp",
  "img/gen/leg-curl-standing.webp",
  "img/gen/leg-extension-ankle.webp",
  "img/gen/leg-extension-both.webp",
  "img/gen/leg-extension-cable.webp",
  "img/gen/leg-extension-iso.webp",
  "img/gen/leg-extension-single.webp",
  "img/gen/leg-press-45.webp",
  "img/gen/leg-press-90.webp",
  "img/gen/leg-press-horizontal.webp",
  "img/gen/leg-swings.webp",
  "img/gen/lizard.webp",
  "img/gen/low-lunge.webp",
  "img/gen/lunge-halfsplit-flow.webp",
  "img/gen/lunge-pulses.webp",
  "img/gen/negative-pull-up.webp",
  "img/gen/ninety-ninety.webp",
  "img/gen/pancake-fold.webp",
  "img/gen/pec-deck.webp",
  "img/gen/pigeon.webp",
  "img/gen/point-flex.webp",
  "img/gen/preacher-curl.webp",
  "img/gen/psoas-march.webp",
  "img/gen/pull-up.webp",
  "img/gen/puppy-pose.webp",
  "img/gen/push-up.webp",
  "img/gen/releve-holds.webp",
  "img/gen/rope-pulldown.webp",
  "img/gen/row-horizontal-machine.webp",
  "img/gen/scapular-pull.webp",
  "img/gen/seated-row-high.webp",
  "img/gen/seated-row-low.webp",
  "img/gen/seated-row-mid.webp",
  "img/gen/side-leg-raise.webp",
  "img/gen/single-leg-hamstring.webp",
  "img/gen/smith-bench-press.webp",
  "img/gen/smith-lunge.webp",
  "img/gen/soleus-stretch.webp",
  "img/gen/sphinx-cobra.webp",
  "img/gen/split-pnf.webp",
  "img/gen/standing-hip-ext.webp",
  "img/gen/standing-quad.webp",
  "img/gen/standing-split.webp",
  "img/gen/straddle-center.webp",
  "img/gen/straddle-side-reach.webp",
  "img/gen/sumo-squat.webp",
  "img/gen/thoracic-rotation.webp",
  "img/gen/toe-stretch-kneel.webp",
  "img/gen/triceps-pushdown-single.webp",
  "img/gen/triceps-pushdown.webp",
  "img/gen/twisted-lizard.webp",
  "img/gen/v-bar-pulldown.webp",
  "img/gen/wall-straddle.webp",
  "img/gen/wide-leg-fold.webp",
  "img/gen/wide-push-up.webp",
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(hit =>
      hit ||
      fetch(e.request).then(res => {
        const copy = res.clone();
        caches.open(VERSION).then(c => c.put(e.request, copy));
        return res;
      }).catch(() => (e.request.mode === "navigate" ? caches.match("./") : undefined))
    )
  );
});
